Repository mschilli/net-google-drive-simple, pull requests merged in 2019-01, with the labels that each got.

#17 Added cpanfile and README.pod
  .gitignore
  README.pod
  cpanfile
  lib/Net/Google/Drive/Simple.pm
Labels: Documentation

#15 Add file_metadata() method
  README
  lib/Net/Google/Drive/Simple.pm
  t/001Basic.t
Labels: enhancement

#14 Fix second return value for children
  lib/Net/Google/Drive/Simple.pm
Labels: bug
